### ISSUE TITLE
Talked to Ted

### ISSUE THREAD

**Issue by NickEBarnes** [dhuang12138/CS2820#11]
In light of new code being used for many of the different files. I spoke with Ted, he said that we should work on our copies of the code that are in the unitTesting part of the production folder and we will be graded on that. Thought you guys might like to know. If you guys are missing any code you can run 

 git reset ____________       (put the hex code that is in the list of commits from the list of everyones commits)

**Comment by ghost** [comment]
I'll say that the code in production looks very good and I'm glad Di was able to make something that runs. The code seems pretty similar to that of production_unittest but since it's not authored by us we can't get credit for it. It would be very helpful if we could import that as a project onto our own computers and edit and contribute to that so that we can at least be co-authors.

**Comment by NickEBarnes** [comment]
Does it run? I can't get anything to test at all

**Comment by NickEBarnes** [comment]
Ted said to just make sure for the project paper to say what happened and where he can find what files are yours. I wouldn't touch any of the new stuff and just continue working on your old stuff and get it to do something. Just some console output would probably be fine

**Comment by NickEBarnes** [comment]
Or do whatever, your call

**Comment by ghost** [comment]
I assume that it runs because Di says it does, but I'm unable to import it as a project onto my computer to try it myself. If I can get it on my computer I will edit it because that I way i'll be able to test if any changes I make brake the code, otherwise I will continue to contribute to prod_unittest I guess. From looking at it, Production is just a working version of Prod_unittest, it's structurally the same.

**Comment by NickEBarnes** [comment]
Well I am trying to work with the production_unitTesting folder but it is completely messed up, there are missing classes, missing code everywhere. I really wish this whole thing had been discussed. Hopefully whoever did it will show up Thursday to say what they did

**Comment by di-huang** [comment]
Yes, I think your individual contributions will be graded by unit testing, so you have to prepare your own test files under production_unitTesting file (like TestMaster.java, TestRobot.java...). However, what we're gonna show at the demo day is a runnable final production, which is totally different and without any errors (better no any bugs), unless you want to show everybody a crashed program, which is integration test! I am responsible for making it run successfully by the demo day, so I finished your parts  by my design pattern. Currently, the simulation program should run without any errors if you pull or download and import correctly (I have posted a copy zip on one of issues, and you can test it!!).

**Comment by di-huang** [comment]
@NickEBarnes @charlesc3929  it does work successfully. If you want to see, I can show you at a face-to-face meeting.
<img width="592" alt="screen shot 2016-12-06 at 7 45 49 pm" src="https://cloud.githubusercontent.com/assets/23122084/20951659/ad4477a6-bbec-11e6-827e-846182ddc90e.png">
<img width="644" alt="screen shot 2016-12-06 at 7 45 54 pm" src="https://cloud.githubusercontent.com/assets/23122084/20951661/ad5e5220-bbec-11e6-83b0-57ed3a437695.png">
<img width="592" alt="screen shot 2016-12-06 at 7 45 57 pm" src="https://cloud.githubusercontent.com/assets/23122084/20951660/ad5df636-bbec-11e6-923b-604e56d26bc7.png">
<img width="605" alt="screen shot 2016-12-06 at 7 46 00 pm" src="https://cloud.githubusercontent.com/assets/23122084/20951662/ad615fa6-bbec-11e6-80db-af7ed3c5c3a2.png">

**Comment by josephLeiferman** [comment]
I have it working on my machine correctly as well.
